### ISSUE TITLE
test run error

### ISSUE THREAD

**Issue by KlaraBogar** [JoseRuedaRueda/uFILDSIM#2]
Hello,

there is an error in the test run. It is trying to find an input field in the Jose IPP home directory.

At line 839 of file sinpa_module.f90 (unit = 60)
Fortran runtime error: Cannot open file '/afs/ipp-garching.mpg.de/home/r/ruejo/SINPA/runs/InitialTest/inputs/field.bin': No such file or directory

There should not be hardcoded paths to the local home directory, which are later disappearing. ;)

**Comment by JoseRuedaRueda** [comment]
Solved in person, was just an issue of reading the docs :)

**Comment by JoseRuedaRueda** [comment]
This is said in the readme
SINPA comes with a test input configuration file. Once your code is compiled, go to the file ./runs/InitialTest/inputs/InitialTest.cfg and change the variables indicated with a !@# in the comments (they are the ones pointing to speficit paths of your installation, runDir and GeomDir
